### PR TITLE
Update projects and NuGet packages to target Excel-DNA v1.0.0

### PR DESCRIPTION
**Pull request by caioproiete**
... as the title says

### CODE REVIEW

**Comment by govert** [comment]
Should we rather make the package version 1.0.0 to match the ExcelDna.AddIn package?

**Comment by caioproiete** [comment]
@govert Yep, works for me.

In fact, moving forward I'd really the versions of all NuGet packages that depend on `ExcelDna.Integration` to be kept in sync...

**Comment by govert** [comment]
The idea previously was not that Registration had to be kept in sync with the main add-in versions and it evolved on its own. It was just the ExcelDna.AddIn and ExcelDna.Integration that were tightly coupled. Registration worked and could be fixed or improved on its own, running on a new enough ExcelDna.Integration. Similar for Intellisense - a small fix there should not need a new core add-in version.
So my suggestion to 'match' the AddIn package version was perhaps misplaced - it should be version 1.0 on its own merit? I did want to move away from the 0.xxxx versions, just not sure about what should be kept in sync going forward. Registration and IntelliSense should probably evolve faster.

**Comment by caioproiete** [comment]
That makes sense to me.

When a new `ExcelDna.Integration` is released, should we release a new version of `Registration` (and `IntelliSense` for that matter) targeting the newly released `ExcelDna.Integration` and updating its dependency?

(and update the `ExcelDna.Integration` dependency version to be `==` instead of `>=`, similar to the [relationship between `ExcelDna.Registration.FSharp` & `ExcelDna.Registration`](https://github.com/Excel-DNA/Registration/blob/master/NuGet/ExcelDna.Registration.FSharp/ExcelDna.Registration.FSharp.nuspec#L19))

**Comment by govert** [comment]
OK - your suggestions make the projects more coupled than they were, but we can see how that works and if it's not good I guess it can change again.

So let's take that as the current policy: after a new version of ExcelDna.Integration, we update ExcelDna.IntelliSense and ExcelDna.Registration to target exactly the new ExcelDna.Integration version as `==`. That still allows us to make sub-versions of ExcelDna.Registration and ExcelDna.IntelliSense at a faster rate, always targeting exactly the newest ExcelDna.Integration.

Does that sound right?
Would that hold for pre-release versions too?
It's a bit strict, but if you think it's OK ...

**Comment by caioproiete** [comment]
@govert Good point about pre-release versions, especially if we'll start publishing them on some NuGet feed via CI soon.

Maybe it's better to leave the dependency not strict (as it is today) and just have as a general goal to try to release new NuGet packages of Registration and IntelliSense when new (final) versions of `ExcelDna.Integration` are published in NuGet.org.

**Pull request merged**
