### PR TITLE
Fixed broken reference to MS XL interops in Registartion.Sample.VisualBasic

### PR DESCRIPTION
**Pull request by masariello**

### CODE REVIEW

**Comment by govert** [comment]
Is there any reason to prefer this over the Excel 2013 interop libraries in the `ExcelDna.Interop` package?

**Comment by govert** [comment]
Sorry - ExcelDna.Interop is Excel 2010. But includes the Office and VBE libraries.

**Comment by govert** [comment]
Why do you think something was broken?

**Comment by govert** [comment]
@masariello I can't see anything that was wrong with the head version of the master branch...?

**Comment by masariello** [comment]
Switched back to Excel-Dna.Interop and now things work.

Some of the HintPaths were wrong. I notice nuget has both an "Excel-Dna.Interop" and an "ExcelDna.Interop" packages. The latter was causing VS2015 to fail to resolve the assembly. Now the projects work and look consistent.

**Comment by govert** [comment]
You might have some weird installation. Those packages are the same - I just standardised the names to "ExcelDna.XXX" at some stage.

I've pushed an update that only uses "ExcelDna.Interop" and builds fine on my machine.

**Comment by masariello** [comment]
Works perfectly now. Thank you!

**Pull request closed without merging**
