### PR TITLE
A tentative implementation of marshal-by-reference semantics aka object handles

### LINKED ISSUE #6: Automatic wrapper generation for object handles
Object handles wrappers provide constructor and access functions for object instances (in contrast with the static methods currently supported by Excel-DNA). It would be convenient to generate these wrappers.

One sample project with an implementation of object handles, with some specialized features like batch updating, can be found in the (Samples repository)[https://github.com/Excel-DNA/Samples/tree/master/ObjectHandles].

Using the RTD / IExcelObservable implementation to provide deterministic lifetime management has proven to be robust.

There are quite a number of design issue to resolve in implementing the wrapper generation. Among these:
* Identifying classes, constructors and methods/properties to generate wrappers for
* Details of the wrappers
* Update processing - INotifyPropertyChanged etc.

I'd welcome discussion and suggestions on what would be useful in this area.

### PR DESCRIPTION
**Pull request by masariello**
This branch also makes Enum conversion work for IEnumerable<Enum> parameters

### CODE REVIEW

**Comment by govert** [comment]
I haven't looked at the code much, though I'd probably like to understand what you are trying to do first.

I like the idea of having a registration option to expose properties and methods from object instances. It would be easier for me to see what the intended usage is it you put some sample formulae as comments in the C# code.

* How do we deal with overloaded constructors?

* Do you mean only interfaces can be exposed via object handles?

* Do you mean only properties are exposed, or all public methods too?

* Are attributes on methods and arguments passed through correctly?

I don't like the "MarshalByRef" term in this context - I'd rather stick to "Object Handles" in some form.

Any object handles implementation should probably take the RTD-based approach to do the lifetime management. There's a great example and write-up in the ACQ add-in. See the links from https://excel-dna.net/2016/06/10/add-in-spotlight-acq-for-interpolation/ There's a detailed write-up on CodeProject too.

If we had this code in ExcelDna.Registration, how much simpler would the ACQ implementation become?

**Comment by masariello** [comment]
The use-cases are exemplified in MarshalByRefExamples.cs and Registartion.Samples.xlsx. The PR is only about object handles. I didn't do anything to auto-expose class constructors, instance properties or methods. One still needs to wrap them manually with static methods the usual way, but the wrapping should become easier. So the idea is basically to support the following signatures, with one important assumption: the objects behind the exported interfaces are assumed **immutable**. An object is created by a function call in a cell. If one of the parameters to the function changes, then the cell is recalculated and a new object is created, which replaces the previous one. The tracking scheme used in this PR can "leak" if a construction formula is moved to a different cell. But that's normally considered acceptable. It's normally enough to provide a CacheClear in-sheet function.
```
[ExcelMarshalByRef]
public interface ISampleMarshalByRefInterface {...}

[ExcelFunction]
public static ISampleMarshalByRefInterface dnaFactorySingle(SomeEnum enumValue, double doubleValue)

[ExcelMapArrayFunction]
public static IEnumerable<ISampleMarshalByRefInterface> dnaMarshalByRef(IEnumerable<ISampleMarshalByRefInterface> objects)
```
The registration config only needs the following:
```
var paramConversionConfig = new ParameterConversionConfiguration()
    .AddReferenceMarshaller(ExcelObjectCache.Instance)
    ...
```

The following is an ACQ function that uses object handles:
```
[ExcelFunction(Description = "Create Interpolator object", Category = AddInInfo.Category)]
public static object acq_interpolator_create(double[] x, double[] y, object method, object bounds)
{
    if (ExcelDnaUtil.IsInFunctionWizard())
        return ExcelError.ExcelErrorRef;
    else
    {
        return ACQ.Excel.Handles.GlobalCache.CreateHandle(m_tag, new object[] { x, y, method, bounds, "acq_interpolator_create" },
            (objectType, parameters) =>
            {
            ...interpolator = construct_interpolator (...);
            });
    }
}
```
With the changes in this PR one should be able to drop all the code related to IExcelObservable and to just expose something like the following:
```
[ExcelMarshalByRef]
interface InterpolationInterface {...}

[ExcelFunction]
public static InterpolationInterface construct_interpolator(double[] x, double y[], string method)
```

**Comment by govert** [comment]
I'm not sure where to draw the line between what I want to support in the 'official' project, vs. what would be cool but just go into your own add-in. While I think the idea of a standard object handle approach would be nice, I think the details need some thought. The interface based approach you have here doesn't really seem (to me) to cover enough of the requirement.

I also think you need to look at the IExcelObservable-based object handle implementation in the ACQ add-in as a basis for the implementation. That deals with a lot of the implementation details better than a cache the needs manual clean-up.

For inspiration on how it might look in the user;s add-in, you might consider what FCell does (http://fcell.io/Help_3_0/Index.html) or what the old ManagedXLL supported (http://www.stochastix.com/solutions/excel/managedxll/latest/features).

**Comment by masariello** [comment]
Hmm. Your reply makes me think it's probably wiser to reduce the scope of the change, and perhaps focus on providing hooks that allow users to pick their preferred way to do object handles, rather than locking into a specific implementation.

I had a good look at what ACQ does and I have the following 2 cencerns about RTD:

1. The current implementation of AsyncCallInfo.ComputeHashCode(object) in ExcelDna would imply restrictions to the variety of types one can pass into any construction functions.
2. In theory one can call one function to create a large number of objects (e.g. what I did with dnaFactoryMultiple in Registration.Sample). I'd prefer to avoid crossing the managed-unmanaged boundary for each object if possible. Unless I'm getting something very valuable in return, and I don't think lifecycle management is enough in this case, because the problem can be solved without incurring the cost (e.g. with IReferenceMarshaler).

I would actually see a scope for both ways of doing object handles (RTD and cell-trackiing) in the same workbook.

Many changes in this branch are actually to do with homogeneous support for IEnumerable<T>, where T is any of the types for which the configuration has a conversion (e.g. Enum types). I will create a smaller PR just for those.

Let's park object handles until then.

**Comment by govert** [comment]
The types supported by `AsyncCallInfo.ComputeHashCode` cover all the possible Excel parameter types. The wrapper that handles the async, streaming or object handles should always be on the outside (to reduce conversions) so this should not be a limitation.

Regarding performance you might have a point, though I haven't seen any numbers, and there is a fair amount of optimization that could in theory be done with the RTD stuff that would benefit all features using it.

**Pull request closed without merging**
